name = "making-something"
compatibility_date = "2024-08-27"
main = "./dist/worker/index.js"

[vars]
PUBLIC_CLERK_PUBLISHABLE_KEY=
CLERK_SECRET_KEY=

## Database connection
DATABASE_URL=

## API
API_URL=

CLERK_WEBHOOK_SIGNING_SECRET=